# -*- coding: utf-8 -*-
"""Speech understanding Question1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1McMeL0yopusUBNgAVdJ0pLNDzkxQMUZi

**Question 1 Solution**

**1. mfcc_manual.py**
"""

# ===============================
# INSTALL (run once in Colab)
# ===============================
!pip install datasets

# ===============================
# IMPORTS
# ===============================
import numpy as np
import matplotlib.pyplot as plt
import scipy.fftpack as fftpack
from scipy.signal import spectrogram
from datasets import load_dataset

# ===============================
# STEP 0: LOAD DATASET
# ===============================
def load_sample_audio():
    dataset = load_dataset("librispeech_asr", "clean", split="validation[:1]")
    audio = dataset[0]["audio"]["array"]
    sr = dataset[0]["audio"]["sampling_rate"]
    return sr, audio


# ===============================
# STEP 1: PRE-EMPHASIS
# ===============================
def pre_emphasis(signal, alpha=0.97):
    return np.append(signal[0], signal[1:] - alpha * signal[:-1])


# ===============================
# STEP 2: FRAMING
# ===============================
def framing(signal, sr, frame_size=0.025, frame_stride=0.01):
    frame_length = int(frame_size * sr)
    frame_step = int(frame_stride * sr)

    signal_length = len(signal)
    num_frames = int(np.ceil(float(np.abs(signal_length - frame_length)) / frame_step))

    pad_signal_length = num_frames * frame_step + frame_length
    pad_signal = np.append(signal, np.zeros(pad_signal_length - signal_length))

    indices = np.tile(np.arange(0, frame_length), (num_frames, 1)) + \
              np.tile(np.arange(0, num_frames * frame_step, frame_step), (frame_length, 1)).T

    return pad_signal[indices.astype(np.int32, copy=False)]


# ===============================
# STEP 3: WINDOWING
# ===============================
def apply_window(frames, window_type="hamming"):
    if window_type == "hamming":
        window = np.hamming(frames.shape[1])
    elif window_type == "hanning":
        window = np.hanning(frames.shape[1])
    else:
        window = np.ones(frames.shape[1])

    return frames * window


# ===============================
# STEP 4: FFT + POWER SPECTRUM
# ===============================
def power_spectrum(frames, NFFT=512):
    mag_frames = np.absolute(np.fft.rfft(frames, NFFT))
    return (1.0 / NFFT) * (mag_frames ** 2)


# ===============================
# STEP 5: MEL FILTERBANK
# ===============================
def mel_filterbank(pow_frames, sr, nfilt=26, NFFT=512):
    low_mel = 0
    high_mel = 2595 * np.log10(1 + (sr / 2) / 700)

    mel_points = np.linspace(low_mel, high_mel, nfilt + 2)
    hz_points = 700 * (10**(mel_points / 2595) - 1)

    bins = np.floor((NFFT + 1) * hz_points / sr)

    fbank = np.zeros((nfilt, int(NFFT / 2 + 1)))

    for m in range(1, nfilt + 1):
        f_m_minus = int(bins[m - 1])
        f_m = int(bins[m])
        f_m_plus = int(bins[m + 1])

        for k in range(f_m_minus, f_m):
            fbank[m - 1, k] = (k - bins[m - 1]) / (bins[m] - bins[m - 1])

        for k in range(f_m, f_m_plus):
            fbank[m - 1, k] = (bins[m + 1] - k) / (bins[m + 1] - bins[m])

    filter_banks = np.dot(pow_frames, fbank.T)
    filter_banks = np.where(filter_banks == 0, np.finfo(float).eps, filter_banks)

    return np.log(filter_banks)


# ===============================
# STEP 6: DCT → MFCC
# ===============================
def compute_mfcc(log_mel, num_ceps=13):
    return fftpack.dct(log_mel, type=2, axis=1, norm='ortho')[:, :num_ceps]


# ===============================
# FULL PIPELINE
# ===============================
def extract_mfcc():
    sr, audio = load_sample_audio()

    emphasized = pre_emphasis(audio)
    frames = framing(emphasized, sr)
    windowed = apply_window(frames, "hamming")
    power = power_spectrum(windowed)
    mel = mel_filterbank(power, sr)
    mfcc = compute_mfcc(mel)

    return mfcc, audio, sr


# ===============================
# VISUALIZATION
# ===============================
def plot_mfcc(mfcc):
    plt.figure(figsize=(10, 4))
    plt.imshow(mfcc.T, aspect='auto', origin='lower')
    plt.title("MFCC Features")
    plt.xlabel("Frames")
    plt.ylabel("Coefficients")
    plt.colorbar()
    plt.tight_layout()
    plt.show()


def plot_spectrogram(signal, sr):
    f, t, Sxx = spectrogram(signal, sr)

    plt.figure(figsize=(10, 4))
    plt.pcolormesh(t, f, 10 * np.log10(Sxx + 1e-10))
    plt.title("Spectrogram")
    plt.xlabel("Time")
    plt.ylabel("Frequency")
    plt.colorbar(label="Intensity (dB)")
    plt.tight_layout()
    plt.show()


# ===============================
# RUN EVERYTHING
# ===============================
mfcc, signal, sr = extract_mfcc()

print("MFCC shape:", mfcc.shape)

plot_mfcc(mfcc)
plot_spectrogram(signal, sr)

"""**leakage_snr.py**

**(Spectral leakage + SNR comparison)**
"""

# ===============================
# INSTALL (run once)
# ===============================
!pip install datasets

# ===============================
# IMPORTS
# ===============================
import numpy as np
import matplotlib.pyplot as plt
from datasets import load_dataset

# ===============================
# LOAD AUDIO
# ===============================
def load_sample_audio():
    dataset = load_dataset("librispeech_asr", "clean", split="validation[:1]")
    audio = dataset[0]["audio"]["array"]
    sr = dataset[0]["audio"]["sampling_rate"]
    return sr, audio


# ===============================
# WINDOW FUNCTIONS
# ===============================
def apply_window(signal, window_type):
    N = len(signal)

    if window_type == "hamming":
        return signal * np.hamming(N)
    elif window_type == "hanning":
        return signal * np.hanning(N)
    else:
        return signal  # rectangular


# ===============================
# FFT
# ===============================
def compute_fft(signal):
    return np.fft.fft(signal)


# ===============================
# SPECTRAL LEAKAGE (PROPER)
# ===============================
def compute_leakage(signal):
    spectrum = np.abs(compute_fft(signal))**2

    peak_idx = np.argmax(spectrum)
    main_energy = spectrum[peak_idx]

    total_energy = np.sum(spectrum)

    leakage = total_energy - main_energy
    leakage_ratio = leakage / total_energy

    return leakage_ratio


# ===============================
# SNR
# ===============================
def compute_snr(clean, noisy):
    noise = noisy - clean
    snr = 10 * np.log10(np.sum(clean**2) / (np.sum(noise**2) + 1e-10))
    return snr


# ===============================
# ANALYSIS FUNCTION
# ===============================
def analyze_windows(signal):
    windows = ["rectangular", "hamming", "hanning"]

    leakage_vals = []
    snr_vals = []

    for w in windows:
        windowed = apply_window(signal, w)

        # Leakage
        leakage = compute_leakage(windowed)

        # Add controlled noise
        noise = 0.01 * np.random.randn(len(signal))
        noisy = windowed + noise

        snr = compute_snr(windowed, noisy)

        leakage_vals.append(leakage)
        snr_vals.append(snr)

        print(f"{w.upper()} → Leakage: {leakage:.6f}, SNR: {snr:.2f} dB")

    return windows, leakage_vals, snr_vals


# ===============================
# PLOTS (REPORT QUALITY)
# ===============================
def plot_results(windows, leakage_vals, snr_vals):

    # Leakage plot
    plt.figure(figsize=(8, 4))
    plt.bar(windows, leakage_vals)
    plt.title("Spectral Leakage Comparison")
    plt.xlabel("Window Type")
    plt.ylabel("Leakage Ratio")
    plt.grid(axis='y')
    plt.show()

    # SNR plot
    plt.figure(figsize=(8, 4))
    plt.bar(windows, snr_vals)
    plt.title("Signal-to-Noise Ratio (SNR) Comparison")
    plt.xlabel("Window Type")
    plt.ylabel("SNR (dB)")
    plt.grid(axis='y')
    plt.show()


# ===============================
# RUN
# ===============================
sr, audio = load_sample_audio()

# Use a short segment for fair comparison
signal = audio[:2048]

windows, leakage_vals, snr_vals = analyze_windows(signal)

plot_results(windows, leakage_vals, snr_vals)

"""3. voiced_unvoiced.py

(Cepstrum-based segmentation)
"""

# ===============================
# INSTALL (run once)
# ===============================
!pip install datasets

# ===============================
# IMPORTS
# ===============================
import numpy as np
import matplotlib.pyplot as plt
from datasets import load_dataset

# ===============================
# LOAD AUDIO
# ===============================
def load_sample_audio():
    dataset = load_dataset("librispeech_asr", "clean", split="validation[:1]")
    audio = dataset[0]["audio"]["array"]
    sr = dataset[0]["audio"]["sampling_rate"]
    return sr, audio


# ===============================
# PRE-EMPHASIS
# ===============================
def pre_emphasis(signal, alpha=0.97):
    return np.append(signal[0], signal[1:] - alpha * signal[:-1])


# ===============================
# FRAMING
# ===============================
def framing(signal, sr, frame_size=0.025, frame_stride=0.01):
    frame_length = int(frame_size * sr)
    frame_step = int(frame_stride * sr)

    signal_length = len(signal)
    num_frames = int(np.ceil(float(np.abs(signal_length - frame_length)) / frame_step))

    pad_signal_length = num_frames * frame_step + frame_length
    pad_signal = np.append(signal, np.zeros(pad_signal_length - signal_length))

    indices = np.tile(np.arange(0, frame_length), (num_frames, 1)) + \
              np.tile(np.arange(0, num_frames * frame_step, frame_step), (frame_length, 1)).T

    return pad_signal[indices.astype(np.int32, copy=False)]


# ===============================
# CEPSTRUM COMPUTATION
# ===============================
def compute_cepstrum(frame):
    spectrum = np.fft.fft(frame)
    log_spectrum = np.log(np.abs(spectrum) + 1e-10)
    cepstrum = np.fft.ifft(log_spectrum).real
    return cepstrum


# ===============================
# VOICED / UNVOICED CLASSIFICATION
# ===============================
def classify_frame(cepstrum, threshold=0.02):
    # Low quefrency → vocal tract (envelope)
    low_q = np.mean(np.abs(cepstrum[:20]))

    # High quefrency → pitch periodicity
    high_q = np.mean(np.abs(cepstrum[20:100]))

    if high_q > threshold:
        return 1  # voiced
    else:
        return 0  # unvoiced


# ===============================
# SEGMENT SIGNAL
# ===============================
def segment_signal(signal, sr):
    frames = framing(signal, sr)
    labels = []

    for frame in frames:
        cep = compute_cepstrum(frame)
        label = classify_frame(cep)
        labels.append(label)

    return np.array(labels), frames


# ===============================
# VISUALIZATION (VERY IMPORTANT)
# ===============================
def plot_voiced_unvoiced(signal, sr, labels, frame_size=0.025, frame_stride=0.01):

    frame_length = int(frame_size * sr)
    frame_step = int(frame_stride * sr)

    time_axis = np.arange(len(signal))

    plt.figure(figsize=(12, 4))
    plt.plot(time_axis, signal, label="Speech Signal")

    for i, label in enumerate(labels):
        if label == 1:
            start = i * frame_step
            end = start + frame_length
            plt.axvspan(start, end, alpha=0.2)

    plt.title("Voiced (Highlighted) vs Unvoiced Segments")
    plt.xlabel("Samples")
    plt.ylabel("Amplitude")
    plt.legend()
    plt.tight_layout()
    plt.show()


# ===============================
# RUN
# ===============================
sr, audio = load_sample_audio()

# Pre-emphasis improves clarity
audio = pre_emphasis(audio)

labels, frames = segment_signal(audio, sr)

print("Total Frames:", len(labels))
print("Voiced Frames:", np.sum(labels))
print("Unvoiced Frames:", len(labels) - np.sum(labels))

plot_voiced_unvoiced(audio, sr, labels)

"""4. phonetic_mapping.py

(Hugging Face + RMSE calculation)
"""

# ===============================
# INSTALL (run once)
# ===============================
!pip install datasets transformers soundfile torch

# ===============================
# IMPORTS
# ===============================
import numpy as np
import torch
import matplotlib.pyplot as plt
from datasets import load_dataset
from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC

# ===============================
# LOAD AUDIO
# ===============================
def load_sample_audio():
    dataset = load_dataset("librispeech_asr", "clean", split="validation[:1]")
    audio = dataset[0]["audio"]["array"]
    sr = dataset[0]["audio"]["sampling_rate"]
    return sr, audio


# ===============================
# LOAD MODEL
# ===============================
def load_model():
    processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")
    model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")
    return processor, model


# ===============================
# MODEL BOUNDARIES
# ===============================
def get_model_boundaries(audio, sr, processor, model):

    inputs = processor(audio, sampling_rate=sr, return_tensors="pt", padding=True)

    with torch.no_grad():
        logits = model(inputs.input_values).logits

    pred_ids = torch.argmax(logits, dim=-1)

    transcription = processor.batch_decode(pred_ids)[0]

    # Time mapping
    num_frames = logits.shape[1]
    duration = len(audio) / sr
    time_per_frame = duration / num_frames

    boundaries = np.arange(0, duration, time_per_frame)

    return boundaries, transcription


# ===============================
# MANUAL BOUNDARIES
# ===============================
def get_manual_boundaries(audio, sr, frame_stride=0.01):
    duration = len(audio) / sr
    return np.arange(0, duration, frame_stride)


# ===============================
# RMSE WITH ALIGNMENT (FIXED)
# ===============================
def compute_rmse(manual, model):

    # Make both same length using interpolation
    target_len = min(len(manual), len(model))

    manual_resampled = np.interp(
        np.linspace(0, len(manual), target_len),
        np.arange(len(manual)),
        manual
    )

    model_resampled = np.interp(
        np.linspace(0, len(model), target_len),
        np.arange(len(model)),
        model
    )

    rmse = np.sqrt(np.mean((manual_resampled - model_resampled) ** 2))

    return rmse, manual_resampled, model_resampled


# ===============================
# VISUALIZATION
# ===============================
def plot_boundaries(manual, model):

    plt.figure(figsize=(10, 4))

    plt.plot(manual, label="Manual Boundaries", marker='o', markersize=3)
    plt.plot(model, label="Model Boundaries", marker='x', markersize=3)

    plt.title("Boundary Alignment Comparison")
    plt.xlabel("Frame Index")
    plt.ylabel("Time (seconds)")
    plt.legend()
    plt.grid()
    plt.tight_layout()
    plt.show()


# ===============================
# RUN PIPELINE
# ===============================
sr, audio = load_sample_audio()

processor, model = load_model()

model_boundaries, transcription = get_model_boundaries(audio, sr, processor, model)

manual_boundaries = get_manual_boundaries(audio, sr)

rmse, manual_aligned, model_aligned = compute_rmse(manual_boundaries, model_boundaries)

print("Transcription:\n", transcription)
print("\nRMSE:", rmse)

plot_boundaries(manual_aligned, model_aligned)